### ISSUE TITLE
A word about "significance"

### ISSUE THREAD

**Issue by cviddy17** [V13J0/Biodiversity-for-the-National-Parks#3]
The solutions provided were correct, but we must always be careful in what we call different when talking about statistical significance.

The p-values given are all correct, and determining significant vs non-significant was also correct, but the idea behind significance is that if this value is significant, it means that there is a difference and if it is not significance, there is insufficient data showing the difference. This gives meaning to hypothesis testing.

**Comment by cviejom** [comment]
Thanks for the explanations around this topic, I will keep this in mind.
